### ISSUE TITLE
Did not get a plausible value

### ISSUE THREAD

**Issue by christianmeichtry** [lexruee/swissgrid#1]
```
1.9.3-p194 :021 > ch1903_point = [611202,177630] # Thun
 => [611202, 177630]
1.9.3-p194 :022 > wgs84_coord =  Swissgrid::WGS84(ch1903_point)
 => [531.6424544095668, 1467.0217293664757]
1.9.3-p194 :023 >
```

Maybe I'm doing something wrong ?

**Comment by lexruee** [comment]
@christianmeichtry Thanks for the bug report.

In a seminar project I only needed the wgs => ch1903 conversion :-).

The bug should be fixed in commit: https://github.com/lexruee/swissgrid/commit/970a74e84cd8d6665f37798d599ca6261bc9edbb

Your example is now covered in a [test](https://github.com/lexruee/swissgrid/blob/master/spec/swissgrid_spec.rb).

**Comment by christianmeichtry** [comment]
Thanks a lot, everything works nicely now.
